name: helloworld action

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
        #os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v4


      - name: linux make
        if: runner.os == 'Linux'
        run: |
          echo "Building helloworld "
          make
          ls -lR

      - name: windows make
        if: runner.os == 'Windows'
        run: |
          echo "This is Windows OS"
          dir
          cmd /c "set"
          cmd /c "C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe"
          call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/vc/auxiliary/build/vcvars64.bat"
          cl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: helloworld
          path: ./helloworld

      - name: upload to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: bin/linux/helloworld
          message: 'Binary for Linux'

      - name: upload to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/linux/helloworld
