name: helloworld action

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses : litalide/action-helloworld

      - run : echo "xxx0 ${{ inputs.versions }}"
      - run : echo "xxx1 ${{ inputs.version }}"
      - run : echo "xxx2 ${{ inputs.version1 }}"
      - run : ls -l

      - name: Checkout the repo
        uses: actions/checkout@v4

      #- name: configure
      #run: ./configure

      - name: make
        run: |
          echo xxx
          echo "Building helloworld version ${{ inputs.version }}"
          echo "1  ${{ inputs.version.description }}"
          echo "2  $INPUTS_VERSION"
          make
          ls -l

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: helloworld
          path: ./helloworld

      - name: upload to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: bin/linux/helloworld
          message: 'Binary for Linux'
