name: helloworld action

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    #- name: configure
    #run: ./configure

    - name: make
      run: |
        make
        ls -l

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: helloworld
        path: ./helloworld

    - name: upload to repo
      uses: EndBug/add-and-commit@v9
      with:
        add: bin/linux/helloworld
        message: 'Binary for Linux'
